sudo: false
language: python
python:
- '3.5'
env:
  global:
  - SOURCE_BRANCH: master
  - TARGET_BRANCH: gh-pages
  - COMMIT_AUTHOR_EMAIL: marhje52@kth.se
install: pip3 install -r requirements.txt
before_script:
- "./scripts/before"
script: "./scripts/test"
after_success:
- "./scripts/deploy"
before_install:
- openssl aes-256-cbc -K $encrypted_d65680b40eb9_key -iv $encrypted_d65680b40eb9_iv
  -in cyto-github-deploy.enc -out cyto-github-deploy -d
